export const ventures = [
  {
    id: 1, num: "01",
    name: "GoBongo Shop",
    tagline: "Grocery & Lifestyle Commerce",
    sectorKey: "commerce", sectorLabel: "E-Commerce · Grocery",
    desc: "UAE-based online grocery and lifestyle marketplace delivering beverage, grocery and daily essentials across the UAE. Partner network available for B2B accounts.",
    geo: "Dubai, Abu Dhabi, UAE", url: "https://gobongo.shop",
    logo: "/logos/bongologo.png",
    logoBg: "#000000", accent: "#1B4FD8",
    accentLight: "rgba(27,79,216,0.09)", accentBorder: "rgba(27,79,216,0.2)",
    tags: ["Grocery", "Beverages", "UAE Delivery", "B2B Partner"],
    founder: "",
    stat1: { val: "10K+", label: "Orders" }, stat2: { val: "UAE", label: "HQ" },
    featured: true, darkLogo: true,
    sparkPoints: [28, 35, 42, 38, 55, 63, 70, 85],
    featCategories: ["Grocery", "Beverages", "Essentials", "B2B Partner", "UAE Wide"],
  },
  {
    id: 2, num: "02",
    name: "Hooqx LLC",
    tagline: "Digital Transformation Agency",
    sectorKey: "tech", sectorLabel: "IT & Digital Services",
    desc: "US-based full-service digital agency offering web & app development, software engineering, UI/UX design, SEO, social media and performance marketing.",
    geo: "United States", url: "https://hooqx.com",
    logo: "/logos/hooqxlogo.png",
    logoBg: "#000000", accent: "#7C3AED",
    accentLight: "rgba(124,58,237,0.09)", accentBorder: "rgba(124,58,237,0.2)",
    founder: "MD. Sharique Furqan",
    tags: ["Web Dev", "App Dev", "UI/UX Design", "Performance Marketing"],
    stat1: { val: "80+", label: "Clients" }, stat2: { val: "USA", label: "Base" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 3, num: "03",
    name: "CallTawk",
    tagline: "Business Communications Platform",
    sectorKey: "tech", sectorLabel: "Communications Technology",
    desc: "Smarter business communications VoIP, intelligent call management and customer engagement tools purpose-built for modern enterprises across multiple industries.",
    geo: "Global", url: "https://calltawk.com",
    logo: "/logos/calltawklogo.png",
    logoBg: "#000000", accent: "#6D28D9",
    accentLight: "rgba(109,40,217,0.08)", accentBorder: "rgba(109,40,217,0.18)",
    founder: "Sami Ahmed",
    tags: ["VoIP", "Call Management", "Enterprise", "Multi-Industry"],
    stat1: { val: "5K+", label: "Users" }, stat2: { val: "Global", label: "Reach" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 4, num: "04",
    name: "GMI Trading",
    tagline: "Food Distribution Powerhouse",
    sectorKey: "trade", sectorLabel: "Commodity Trading · FMCG",
    desc: "UAE-based food distribution specialist (Grains, Mills & Industries) sugar, rice, edible oils, flour, pulses, spices, snacks & energy drinks. Tech-powered JIT delivery to 10,000+ UAE retail, wholesale & HORECA customers.",
    geo: "Dubai, UAE", url: "https://www.gmitrading.me",
    logo: "/logos/gmilogo.png",
    logoBg: "#000000", accent: "#16a34a",
    accentLight: "rgba(22,163,74,0.09)", accentBorder: "rgba(22,163,74,0.2)",
    founder: "",
    tags: ["Grains", "Edible Oils", "Avocado Farming", "HORECA", "UAE"],
    stat1: { val: "10K+", label: "Customers" }, stat2: { val: "UAE", label: "Market" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 5, num: "05",
    name: "Tezz Logistics",
    tagline: "India's Last-Mile Delivery Network",
    sectorKey: "trade", sectorLabel: "Logistics & Supply Chain",
    desc: "Fast-growing Indian logistics company offering warehousing, first-mile, last-mile and express delivery solutions purpose-built for India's booming e-commerce ecosystem.",
    geo: "India", url: "https://tezzlogistics.in",
    logo: "/logos/tezzlogo.png",
    logoBg: "#000000", accent: "#DC2626",
    accentLight: "rgba(220,38,38,0.08)", accentBorder: "rgba(220,38,38,0.18)",
    founder: "Shadab Ahmed Shah",
    tags: ["Warehousing", "First Mile", "Last Mile", "Express Delivery"],
    stat1: { val: "50+", label: "Cities" }, stat2: { val: "India", label: "Ops" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 6, num: "06",
    name: "Stratigi 360",
    tagline: "Business Setup & Growth Consultancy",
    sectorKey: "consulting", sectorLabel: "Business Consulting · UAE",
    desc: "Dubai-based business setup and management consultancy company formation, UAE licensing, PRO services, accounting, and worry-free end-to-end support for businesses entering the UAE market.",
    geo: "Dubai, UAE", url: "https://stratigi360.com",
    logo: "/logos/stratigi360logo.png",
    logoBg: "#000000", accent: "#E11D48",
    accentLight: "rgba(225,29,72,0.08)", accentBorder: "rgba(225,29,72,0.18)",
    founder: "Sarah Khan",
    tags: ["Business Setup", "UAE Licensing", "PRO Services", "Accounting"],
    stat1: { val: "500+", label: "Businesses" }, stat2: { val: "Dubai", label: "Base" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 7, num: "07",
    name: "Tradeflink",
    tagline: "B2B Cross-Border Trade Platform",
    sectorKey: "trade", sectorLabel: "B2B Trade · Fintech",
    desc: "Connecting buyers and suppliers across borders with streamlined B2B procurement infrastructure and trade facilitation built for the Middle East and Asian markets.",
    geo: "Middle East & Asia", url: "https://www.tradeflink.com",
    logo: "/logos/tradeflinklogo.png",
    logoBg: "#000000", accent: "#1A56E8",
    accentLight: "rgba(26,86,232,0.08)", accentBorder: "rgba(26,86,232,0.18)",
    founder: "",
    tags: ["B2B", "Procurement", "Cross-Border", "Trade Finance"],
    stat1: { val: "200+", label: "Partners" }, stat2: { val: "ME+Asia", label: "Market" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
  {
    id: 8, num: "08",
    name: "Scooda",
    tagline: "B2B Cross-Border Trade Platform",
    sectorKey: "trade", sectorLabel: "B2B Trade · Fintech",
    desc: "Connecting buyers and suppliers across borders with streamlined B2B procurement infrastructure and trade facilitation built for the Middle East and Asian markets.",
    geo: "Middle East & Asia", url: "https://www.tradeflink.com",
    logo: "/logos/scoodalogo.png",
    logoBg: "#000000", accent: "#1A56E8",
    accentLight: "rgba(26,86,232,0.08)", accentBorder: "rgba(26,86,232,0.18)",
    founder: "Aftab Ahmed",
    tags: ["B2B", "Procurement", "Cross-Border", "Trade Finance"],
    stat1: { val: "200+", label: "Partners" }, stat2: { val: "ME+Asia", label: "Market" },
    featured: false, darkLogo: true, sparkPoints: [],
  },
];

export const filters = [
  { key: "all",        label: "All Ventures", count: 7 },
  { key: "commerce",   label: "E-Commerce",     count: 1 },
  { key: "tech",       label: "Tech",         count: 2 },
  { key: "trade",      label: "Trade",        count: 3 },
  { key: "consulting", label: "Consulting",   count: 1 },
];
